Suggested fix for `NoClassDefFoundError: com/intellij/psi/util/PsiTreeUtilKt`, #70. Don't use `com.intellij.psi.util.parentOfType` extension, because it is in `java-lang` module and not available in non-java IDE's (e.g. PyCharm)